import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Loader from "./components/Loader/Loader";
import WhatsAppFloat from "./components/WhatsAppFloat/WhatsAppFloat";
import MobileCardReveal from "./components/MobileCardReveal/MobileCardReveal";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Loader />
        {children}
        <WhatsAppFloat />
        <MobileCardReveal />
      </body>
    </html>
  );
}
